application: test-ttf-on-gae
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

skip_files:
- .*\.rst
- ^(.*/)?#.*#
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*~
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml

handlers:
# Special case for .ttf files needing specific mime_type
# to enjoy gzip encoding/compression from GAE hosting.
# Order is important: this must precede "/p/" static_dir
- url: /p/(.*\.ttf)
  static_files: static/\1
  upload: static/(.*\.ttf)
  mime_type: font/ttf
  expiration: 1000d

- url: /p/
  static_dir: static/
  expiration: 1000d

- url: /.*
  script: main.app
